[package]
name = "hashsigs-rs"
version = "0.0.1"
edition = "2021"
authors = ["Richard T. Carback III <rick.carback@gmail.com>"]
description = "Hash based signatures, WOTS+"
license = "AGPL-3.0"

[lib]
name = "hashsigs_rs"
path = "src/lib.rs"

[workspace]
members = [
    "solana"
]

[dependencies]
getrandom = { version = "0.2", features = ["custom"] }

[dev-dependencies]
solana-sdk="2.2"
solana-program = "2.2"
serde_json = "1.0.89"
