[package]
name = "hashsigs-rs"
version = "0.0.1"
edition = "2021"
authors = ["Richard T. Carback III <rick.carback@gmail.com>"]
description = "Hash based signatures, WOTS+"
license = "AGPL-3.0"

[dependencies]
solana-program = "1.17"
serde_json = "1.0"

[dev-dependencies]
solana-program = "1.17"
serde_json = "1.0"
