[package]
name = "hashsigs-rs"
version = "0.0.2"
edition = "2021"
authors = ["Richard T. Carback III <rick.rust.cargo.383d5@passmail.net>"]
description = "Hash based signatures, WOTS+"
license = "AGPL-3.0-or-later"
repository = "https://github.com/quipnetwork/hashsigs-rs"
documentation = "https://docs.rs/hashsigs-rs"
readme = "README.md"
keywords = ["cryptography", "wots", "signature", "solana"]
categories = ["cryptography", "authentication"]

[lib]
name = "hashsigs_rs"
path = "src/lib.rs"

[workspace]
members = [
    "solana"
]

[dependencies]

[dev-dependencies]
solana-program = "2.3"
serde_json = "1.0.143"
