# Copyright (C) 2026 quip.network
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""PEP 517 build backend: stage the per-profile extensions, then call maturin.

The wheel carries one compiled extension per SHRINCS profile. maturin builds
exactly one Cargo package, and one Cargo package builds at most one cdylib, so
the other extensions have to be built and placed into the package tree before
maturin runs. This backend is where that happens.

It matters most for a source install. ``pip install hashsigs --no-binary`` calls
this backend from an unpacked sdist, with no shell script and no repository
checkout to lean on, so the staging has to be plain Python that works from the
sdist layout alone. That is why the profile table lives in ``py/profiles.json``
rather than in ``bin/packages.sh``: the sdist has no ``bin/``.

Everything else is delegated to maturin unchanged, except the linux platform
tag: see ``_with_pypi_compatibility``.

Requires a Rust toolchain on the build machine, which is inherent to installing
a Rust extension from source.
"""

from __future__ import annotations

import json
import os
import pathlib
import re
import shutil
import subprocess
import sys

from maturin import *  # noqa: F401,F403  (re-export every hook maturin defines)
from maturin import build_sdist as _maturin_build_sdist
from maturin import build_wheel as _maturin_build_wheel

try:  # maturin exposes this only when editable installs are supported.
    from maturin import build_editable as _maturin_build_editable
except ImportError:  # pragma: no cover - depends on the maturin version
    _maturin_build_editable = None

# This file lives in py/; the project root is its parent.
PY_DIR = pathlib.Path(__file__).resolve().parent
ROOT = PY_DIR.parent
PACKAGE = PY_DIR / "python" / "hashsigs"
TABLE = PY_DIR / "profiles.json"

BANNER = "# GENERATED by py/hashsigs_build.py -- do not edit.\n"
LICENSE = (
    "# Copyright (C) 2026 quip.network\n#\n"
    "# SPDX-License-Identifier: AGPL-3.0-or-later\n"
)


def _load_table() -> tuple[list[dict], str]:
    """Read the profile table, or fail with a message that names the file."""
    if not TABLE.is_file():
        raise RuntimeError(
            f"{TABLE} is missing. It is the canonical list of profiles this "
            "distribution ships, and both the repository build and the sdist "
            "build read it."
        )
    table = json.loads(TABLE.read_text())
    profiles = table["profiles"]
    default = table["default"]
    if not profiles:
        raise RuntimeError(f"{TABLE} lists no profiles")
    if not any(p["key"] == default for p in profiles):
        raise RuntimeError(
            f'{TABLE} names default "{default}", which is not in its own profile list'
        )
    return profiles, default


def _cargo_dylib_name(ext: str) -> str:
    """The file cargo writes for a cdylib named `ext`, per platform."""
    if sys.platform == "win32":
        return f"{ext}.dll"
    if sys.platform == "darwin":
        return f"lib{ext}.dylib"
    return f"lib{ext}.so"


def _extension_suffix() -> str:
    """The suffix CPython will import a stable-ABI extension under.

    The extensions are built with pyo3's ``abi3-py39`` feature, so one build
    serves CPython 3.9 and later. On Windows that is ``.pyd``; elsewhere
    ``.abi3.so``. Getting this wrong produces a shared library CPython simply
    does not see, with no error until the import fails.
    """
    if sys.platform == "win32":
        return ".pyd"
    return ".abi3.so"


def _ensure_workspace_members(profiles: list[dict]) -> None:
    """Make sure the root workspace lists every profile crate.

    In the repository it already does, and this is a no-op. In an unpacked
    sdist it does not: maturin trims the workspace to the dependency closure of
    the package it builds, which is ``py`` and ``py/common``. The profile
    crates ship in the sdist -- pyproject.toml names them under ``include`` --
    but nothing depends on them, so they are dropped from ``members`` and
    ``cargo build -p`` cannot find them.

    Adding them back is preferable to the alternatives. Making each crate its
    own workspace root would give six more lockfiles and drop them out of the
    repository's ``cargo test``; making ``py`` depend on them would link six
    extension modules into one shared library.
    """
    manifest = ROOT / "Cargo.toml"
    text = manifest.read_text()

    wanted = [f"py/profiles/{p['module']}" for p in profiles]
    missing = [w for w in wanted if f'"{w}"' not in text]
    if not missing:
        return

    match = re.search(r"(\[workspace\][^\[]*?members\s*=\s*\[)", text, re.S)
    if match is None:
        raise RuntimeError(
            f"cannot find a [workspace] members list in {manifest}, so the "
            f"profile crates {missing} cannot be registered. This build needs "
            "them to be workspace members; see _ensure_workspace_members."
        )

    insert = "".join(f'\n    "{w}",' for w in missing)
    text = text[: match.end()] + insert + text[match.end() :]
    manifest.write_text(text)
    print(
        f"hashsigs: added {len(missing)} profile crates to the workspace", flush=True
    )


def _build_extensions(profiles: list[dict]) -> None:
    """Compile one cdylib per profile and place it in ``hashsigs/_ext``."""
    _ensure_workspace_members(profiles)

    ext_dir = PACKAGE / "_ext"
    ext_dir.mkdir(parents=True, exist_ok=True)

    target_dir = pathlib.Path(
        os.environ.get("CARGO_TARGET_DIR", ROOT / "target")
    ).resolve()

    for profile in profiles:
        crate = profile["crate"]
        ext = profile["ext"]
        print(f"hashsigs: building {profile['key']} -> {ext}", flush=True)
        subprocess.run(
            ["cargo", "build", "--release", "-p", crate],
            cwd=ROOT,
            check=True,
        )
        built = target_dir / "release" / _cargo_dylib_name(ext)
        if not built.is_file():
            raise RuntimeError(
                f"cargo built {crate} but {built} does not exist. If "
                "CARGO_TARGET_DIR is set, the backend looks there."
            )
        # CPython matches an extension's file stem to its module init symbol,
        # so the cargo `lib` prefix has to go.
        shutil.copy2(built, ext_dir / f"{ext}{_extension_suffix()}")


def _write_python_modules(profiles: list[dict], default: str) -> None:
    """Generate the per-profile modules and the package roots.

    They are identical but for the profile they name, and six hand-copied
    modules drift.
    """
    profiles_dir = PACKAGE / "profiles"
    profiles_dir.mkdir(parents=True, exist_ok=True)

    # The manifest the installed package reads back at runtime, so the tests
    # can check the wheel against the table it was built from.
    (profiles_dir / "profiles.json").write_text(
        json.dumps({"default": default, "profiles": profiles}, indent=2) + "\n"
    )

    for profile in profiles:
        (profiles_dir / f"{profile['module']}.py").write_text(
            _profile_module(profile)
        )

    default_module = next(p["module"] for p in profiles if p["key"] == default)
    names = "\n".join(f"    {p['module']!r}," for p in profiles)
    (profiles_dir / "__init__.py").write_text(
        f'''{BANNER}{LICENSE}"""One module per SHRINCS profile, each carrying its own compiled extension.

Import the profile you want::

    from hashsigs.profiles import {default_module}

Every module exposes the same names. They differ only in what they compute, and
a signature made under one profile does not verify under any other.
"""

#: Every profile module in this package, by module name, in the order
#: py/profiles.json lists them.
PROFILES = (
{names}
)

#: The module a bare ``import hashsigs`` binds to. A module name, so it indexes
#: into :data:`PROFILES`; :data:`hashsigs.PROFILE` is the profile KEY, and
#: :data:`hashsigs.PROFILE_NAME` the SHRINCS profile name. The three differ:
#: ``p128s_q18``, ``128s-q18``, and ``shrincs-128s-q18-keccak`` all name one
#: profile.
DEFAULT_MODULE = {default_module!r}
'''
    )

    ext_imports = "\n".join(f"from . import {p['ext']} as {p['ext']}" for p in profiles)
    (PACKAGE / "_ext").mkdir(parents=True, exist_ok=True)
    (PACKAGE / "_ext" / "__init__.py").write_text(
        f'''{BANNER}{LICENSE}"""The compiled per-profile extensions.

One shared library per profile, rather than one carrying all six. Importing a
profile maps only that profile's code.

Re-exported by name here so a missing or mismatched build fails at import with
a clear name, rather than at the first call.
"""

{ext_imports}
'''
    )

    (PACKAGE / "__init__.py").write_text(_package_root(default, default_module))


def _profile_module(profile: dict) -> str:
    return f'''{BANNER}{LICENSE}"""The ``{profile["key"]}`` SHRINCS profile.

Signatures made under this profile do not verify under any other. Pick one
profile per key and keep it.
"""

from .._api import bind
from .._ext import {profile["ext"]}

#: The import key this module is published under, such as ``"128s-q18"``. Note
#: this is the KEY, not the SHRINCS profile name: the two differ for the 128s
#: keccak profiles. See :data:`PROFILE_NAME`.
PROFILE = "{profile["key"]}"

#: The SHRINCS profile name this module's extension must report. Declared in
#: ``py/profiles.json``, which restates a constant from ``src/profiles/p*.rs``,
#: so it can drift. ``test_profiles.py`` asserts the loaded extension agrees,
#: which is what catches one profile's extension built under another's name.
PROFILE_NAME = "{profile["name"]}"

_profile = bind({profile["ext"]})

profile_name = _profile.profile_name
version = _profile.version
max_stateful_signatures = _profile.max_stateful_signatures
sphincs_plus_c = _profile.sphincs_plus_c
shrincs = _profile.shrincs

__all__ = [
    "PROFILE",
    "PROFILE_NAME",
    "max_stateful_signatures",
    "profile_name",
    "shrincs",
    "sphincs_plus_c",
    "version",
]
'''


def _package_root(default: str, default_module: str) -> str:
    return f'''{BANNER}{LICENSE}"""Hash-based signatures: SHRINCS and SPHINCS+C, backed by hashsigs-rs.

This package carries every SHRINCS profile. The names below are the DEFAULT
profile, ``{default}``::

    from hashsigs import shrincs

Any other profile comes from its own module, and all of them expose the same
names::

    from hashsigs.profiles import p128s_q18

A signature made under one profile does not verify under any other.
"""

from ._api import (
    HashSigsError,
    Profile,
    Shrincs,
    ShrincsKeys,
    ShrincsStateful,
    SphincsPlusC,
    SphincsPlusCKeys,
    SphincsPlusCPublicKey,
    SphincsPlusCSecret,
    StatefulPublicKey,
    shrincs_keys_to_secret_bytes,
)
from ._errors import ERROR_CODES
from ._hashsigs import __version__
from .profiles import DEFAULT_MODULE, PROFILES
from .profiles.{default_module} import (
    PROFILE,
    PROFILE_NAME,
    max_stateful_signatures,
    profile_name,
    shrincs,
    sphincs_plus_c,
    version,
)

__all__ = [
    "DEFAULT_MODULE",
    "ERROR_CODES",
    "HashSigsError",
    "PROFILE",
    "PROFILES",
    "PROFILE_NAME",
    "Profile",
    "Shrincs",
    "ShrincsKeys",
    "ShrincsStateful",
    "SphincsPlusC",
    "SphincsPlusCKeys",
    "SphincsPlusCPublicKey",
    "SphincsPlusCSecret",
    "StatefulPublicKey",
    "__version__",
    "max_stateful_signatures",
    "profile_name",
    "shrincs",
    "shrincs_keys_to_secret_bytes",
    "sphincs_plus_c",
    "version",
]
'''


def stage() -> None:
    """Build every profile extension and generate the modules that bind them.

    Also usable directly, for a development build without going through pip:
    ``python -c "import hashsigs_build; hashsigs_build.stage()"``.
    """
    profiles, default = _load_table()
    _build_extensions(profiles)
    _write_python_modules(profiles, default)
    print(f"hashsigs: staged {len(profiles)} profile extensions", flush=True)


# ── PEP 517 hooks ────────────────────────────────────────────────────────
# Only the wheel hooks stage. An sdist is a source copy, and staging into one
# would ship compiled objects in a source distribution.


# maturin's PEP 517 hook defaults to `--compatibility off`, which tags the
# wheel `linux_x86_64`. PyPI rejects that tag outright: a bare linux tag makes
# no promise about the glibc the extensions need. The maturin *CLI* defaults
# the other way, so `maturin publish` produced an uploadable wheel and
# `python -m build` silently did not. Every wheel this backend builds is meant
# for PyPI, so the default belongs here rather than in each caller's flags.
#
# `pypi` rather than a pinned `manylinux_2_34`: it states the requirement
# (must be uploadable) instead of hardcoding a glibc floor that tracks whichever
# image the release runner happens to use.
def _with_pypi_compatibility(config_settings):
    settings = dict(config_settings or {})
    # A caller that passes build args is driving the platform tag on purpose --
    # cross-compiling, or targeting musl. Do not second-guess it.
    if "maturin.build-args" in settings or "build-args" in settings:
        return settings
    if os.getenv("MATURIN_PEP517_ARGS"):
        return settings
    settings["maturin.build-args"] = ["--compatibility", "pypi"]
    return settings


def build_wheel(wheel_directory, config_settings=None, metadata_directory=None):
    stage()
    return _maturin_build_wheel(
        wheel_directory, _with_pypi_compatibility(config_settings), metadata_directory
    )


def build_sdist(sdist_directory, config_settings=None):
    return _maturin_build_sdist(sdist_directory, config_settings)


if _maturin_build_editable is not None:

    def build_editable(wheel_directory, config_settings=None, metadata_directory=None):
        stage()
        return _maturin_build_editable(
            wheel_directory, config_settings, metadata_directory
        )


if __name__ == "__main__":
    stage()
