[package]
name = "hashsigs-rs-solana"
version = "0.0.1"
edition = "2021"
authors = ["Richard T. Carback III <rick.carback@gmail.com>"]
description = "Solana program for WOTS+"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "2.2"
hashsigs-rs = { path = ".." }
borsh = "1.5"
getrandom = { version = "0.1.16", features = ["dummy"] }
bytemuck = "1.13"
bytemuck_derive = "=1.8.1"  # Pin to version required by solana-hash

[dev-dependencies]
solana-program-test = "2.2"
solana-sdk = "2.2"
tokio = { version = "1.44", features = ["full"] }
solana-logger = "2.2"
