// Public entry point for @quip.network/hashsigs-wasm.
//
// `loadShrincsWasm()` returns the raw wasm module with a uniform,
// env-agnostic interface: the `"browser"` field in package.json swaps the
// Node loader for the browser loader at bundle time, so consumers write the
// same code either way. It stays the low-level escape hatch used by
// `WasmShrincsAccount`.
//
// `loadHashSigs()` is the noble-style entry point: it awaits the same wasm
// module once and returns `{ sphincsPlusC, shrincs, shrincsImportSigningKey }`
// — two plain namespace objects plus one standalone function, all working
// directly with `Uint8Array` — mirroring `@noble/post-quantum`'s call shape
// (`sign(message, ...)`, `verify(signature, message, publicKey)`). The async
// boundary is unavoidable (a `.wasm` module has to be instantiated before any
// of this runs), so unlike noble's fully synchronous API, callers await
// `loadHashSigs()` once and then call every method synchronously.
import { loadShrincsWasm } from "./loader.node.js";
export { loadShrincsWasm };

// The module's shape (functions + classes) is generated by wasm-bindgen from the
// audited Rust. Re-export it as a named type for consumers who want to annotate
// their own variables. The generated `.d.ts` is the single source of truth.
export type ShrincsWasmModule = typeof import("./nodejs/hashsigs_rs.js");

// The serde DTO interfaces generated from the Rust structs (via Tsify), so
// consumers can name the object shapes `WasmShrincsAccount.snapshot()`
// returns and the error codes it (and every other function here) throws.
export type { ShrincsAccountSnapshot, ShrincsErrorCode } from "./nodejs/hashsigs_rs.js";

// The live handle classes, exported TYPE-ONLY. Consumers never construct
// these directly (private constructors — instances come from
// `sphincsPlusCKeygen` / `shrincsKeygen` / `shrincsImportSigningKey`, or
// from the `sphincsPlusC`/`shrincs` wrappers below, which unwrap them into
// plain objects); they only need the names to annotate variables and
// fields. Type-only is also load-bearing for the browser: the `browser`
// exports condition maps the package entry to loader.browser.js, which has
// no runtime class bindings — a VALUE export here would exist in Node and
// silently not exist in browser bundles.
export type {
  WasmShrincsKeys,
  WasmSphincsPlusCKeys,
  WasmShrincsAccount,
} from "./nodejs/hashsigs_rs.js";

// ── noble-style Uint8Array API ──────────────────────────────────────────

/** `sphincsPlusC.keygen()`'s return shape: plain bytes, no live wasm handle. */
export interface SphincsPlusCKeys {
  /** 128 bytes: `statelessSkSeed ‖ statelessPrfSeed ‖ pkSeed ‖ hypertreeRoot`. */
  secretKey: Uint8Array;
  /** 64 bytes: `pkSeed ‖ hypertreeRoot`. */
  publicKey: Uint8Array;
}

/**
 * `shrincs.keygen()`'s return shape. `secretKey` is MUTATED IN PLACE by
 * `shrincs.sign()` — the same `Uint8Array` instance is reused and advanced,
 * it is never replaced. Persist it (e.g. to disk) after every stateful
 * `sign()` call to avoid one-time-leaf reuse on restart.
 */
export interface ShrincsKeys {
  /** 264 bytes; see `ShrincsSigningKey`'s field order in the Rust source. */
  secretKey: Uint8Array;
  /** 164 bytes: `statefulPublicKey ‖ publicKeyCommitment ‖ pkSeed ‖ hypertreeRoot`. */
  publicKey: Uint8Array;
  /** 32 bytes; the value `shrincs.verify()` pins. */
  publicKeyCommitment: Uint8Array;
  /** 64 bytes (`pkSeed ‖ hypertreeRoot`); the value `shrincs.verifyStateless()` pins. */
  statelessPublicKey: Uint8Array;
}

function makeSphincsPlusC(wasm: ShrincsWasmModule) {
  return {
    /** Derive a keypair from a REQUIRED 32-byte seed (no RNG fallback). */
    keygen(seed: Uint8Array): SphincsPlusCKeys {
      const keys = wasm.sphincsPlusCKeygen(seed);
      return { secretKey: keys.secretKey, publicKey: keys.publicKey };
    },
    /** Stateless: never mutates `keys.secretKey`. */
    sign(message: Uint8Array, keys: SphincsPlusCKeys): Uint8Array {
      return wasm.sphincsPlusCSign(message, keys.secretKey);
    },
    verify(signature: Uint8Array, message: Uint8Array, publicKey: Uint8Array): boolean {
      return wasm.sphincsPlusCVerify(signature, message, publicKey);
    },
  };
}

// The wasm free function has no scheme-level default (out-of-range values
// throw `ERR_INVALID_INPUT`); this is the JS-side default noble callers get
// when they omit `maxSignatures`.
const DEFAULT_MAX_STATEFUL_SIGNATURES = 1024;

function makeShrincs(wasm: ShrincsWasmModule) {
  return {
    /**
     * Derive a keypair from a REQUIRED 32-byte seed (no RNG fallback).
     * `maxSignatures` defaults to 1024 when omitted.
     */
    keygen(seed: Uint8Array, maxSignatures = DEFAULT_MAX_STATEFUL_SIGNATURES): ShrincsKeys {
      const keys = wasm.shrincsKeygen(seed, maxSignatures);
      return {
        secretKey: keys.secretKey,
        publicKey: keys.publicKey,
        publicKeyCommitment: keys.publicKeyCommitment,
        statelessPublicKey: keys.statelessPublicKey,
      };
    },
    /**
     * STATEFUL: consumes the next unused leaf and advances `keys.secretKey`
     * IN PLACE (the wasm `&mut` binding writes the advanced counter back
     * into the same `Uint8Array` you pass in). Throws
     * `ERR_STATEFUL_LEAVES_EXHAUSTED` once every leaf is spent — use
     * `signStateless` for unlimited recovery-path signing.
     */
    sign(message: Uint8Array, keys: ShrincsKeys): Uint8Array {
      return wasm.shrincsSign(message, keys.secretKey);
    },
    /** Stateless recovery path: never mutates `keys.secretKey`. */
    signStateless(message: Uint8Array, keys: ShrincsKeys): Uint8Array {
      return wasm.shrincsSignStateless(message, keys.secretKey);
    },
    verify(signature: Uint8Array, message: Uint8Array, publicKeyCommitment: Uint8Array): boolean {
      return wasm.shrincsVerify(signature, message, publicKeyCommitment);
    },
    /**
     * A stateless SHRINCS signature is a SPHINCS+C signature, so this is a
     * direct SPHINCS+C verify. Pass `keys.statelessPublicKey` (the 64-byte
     * `pkSeed ‖ hypertreeRoot`), not the commitment.
     */
    verifyStateless(signature: Uint8Array, message: Uint8Array, statelessPublicKey: Uint8Array): boolean {
      return wasm.shrincsVerifyStateless(signature, message, statelessPublicKey);
    },
  };
}

/**
 * Rebuild a `ShrincsKeys` object from a previously persisted 264-byte
 * `secretKey` (e.g. `keys.secretKey` after several `shrincs.sign()` calls).
 * Recomputes both roots and the commitment from the seeds and rejects any
 * mismatch with `ERR_IMPORT_INVALID`. Accepts an already-exhausted key:
 * stateful signing then throws `ERR_STATEFUL_LEAVES_EXHAUSTED`, but
 * stateless signing still works.
 */
function importShrincsSigningKey(wasm: ShrincsWasmModule, secretKey: Uint8Array): ShrincsKeys {
  const keys = wasm.shrincsImportSigningKey(secretKey);
  return {
    secretKey: keys.secretKey,
    publicKey: keys.publicKey,
    publicKeyCommitment: keys.publicKeyCommitment,
    statelessPublicKey: keys.statelessPublicKey,
  };
}

/** The `sphincsPlusC` namespace object `loadHashSigs()` resolves to. */
export type SphincsPlusC = ReturnType<typeof makeSphincsPlusC>;
/** The `shrincs` namespace object `loadHashSigs()` resolves to. */
export type Shrincs = ReturnType<typeof makeShrincs>;

/**
 * Load the wasm module once and assemble the noble-style `sphincsPlusC` and
 * `shrincs` namespace objects, plus the standalone `shrincsImportSigningKey`
 * helper, on top of it.
 *
 * ```ts
 * const { sphincsPlusC, shrincs } = await loadHashSigs();
 * const keys = sphincsPlusC.keygen(seed);
 * const sig = sphincsPlusC.sign(message, keys);
 * sphincsPlusC.verify(sig, message, keys.publicKey); // true
 * ```
 */
export async function loadHashSigs(): Promise<{
  sphincsPlusC: SphincsPlusC;
  shrincs: Shrincs;
  shrincsImportSigningKey: (secretKey: Uint8Array) => ShrincsKeys;
}> {
  const wasm = await loadShrincsWasm();
  return {
    sphincsPlusC: makeSphincsPlusC(wasm),
    shrincs: makeShrincs(wasm),
    shrincsImportSigningKey: (secretKey: Uint8Array) => importShrincsSigningKey(wasm, secretKey),
  };
}

// ── compile-time conformance (zero emit, zero runtime) ─────────────────────
import type {
  WasmShrincsKeys as _WasmShrincsKeys,
  WasmSphincsPlusCKeys as _WasmSphincsPlusCKeys,
} from "./nodejs/hashsigs_rs.js";

type _Expect<T extends true> = T;
type _equal<A, B> =
  (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2)
    ? true
    : false;

type _ShrincsKeygenMintsWasmShrincsKeys = _Expect<
  _equal<ReturnType<ShrincsWasmModule["shrincsKeygen"]>, _WasmShrincsKeys>
>;
type _SphincsPlusCKeygenMintsWasmSphincsPlusCKeys = _Expect<
  _equal<ReturnType<ShrincsWasmModule["sphincsPlusCKeygen"]>, _WasmSphincsPlusCKeys>
>;
