// Public entry point for @quip.network/hashsigs-wasm.
//
// `loadShrincsWasm()` returns the wasm module with a uniform, env-agnostic
// interface: the `"browser"` field in package.json swaps the Node loader for the
// browser loader at bundle time, so consumers write the same code either way.
export { loadShrincsWasm } from "./loader.node.js";

// The module's shape (functions + classes) is generated by wasm-bindgen from the
// audited Rust. Re-export it as a named type for consumers who want to annotate
// their own variables. The generated `.d.ts` is the single source of truth.
export type ShrincsWasmModule = typeof import("./nodejs/hashsigs_rs.js");

// The serde DTO interfaces generated from the Rust structs (via Tsify), so
// consumers can name the object shapes the wasm functions accept and return.
export type {
  ShrincsPublicKey,
  StatefulSignature,
  StatefulSignResult,
  StatelessSignature,
  ForsSignature,
  ForsEntry,
  // Rust renamed the wasm DTO structs to Wasm*-prefixed names (to disambiguate
  // them from the core crypto types); alias back to the stable public names so
  // consumers' imports keep working.
  WasmWotsCSignature as WotsCSignature,
  WasmHypertreeLayerSignature as HypertreeLayerSignature,
  ActionContext,
  RotationContext,
  StatefulRotationTarget,
  RotationTarget,
  ShrincsExportedSigningKey,
  ShrincsAccountSnapshot,
  ShrincsErrorCode,
} from "./nodejs/hashsigs_rs.js";

// The live handle classes, exported TYPE-ONLY. Consumers never construct
// these (private constructors — instances come from `shrincsKeygen` /
// `shrincsImportSigningKey` / the account factories); they only need the
// names to annotate variables and fields. Type-only is also load-bearing
// for the browser: the `browser` exports condition maps the package entry
// to loader.browser.js, which has no runtime class bindings — a VALUE
// export here would exist in Node and silently not exist in browser
// bundles. (This also spares downstream consumers the
// `ReturnType<ShrincsWasmModule["shrincsKeygen"]>` workaround, needed
// because `InstanceType` rejects private constructors.)
export type {
  WasmShrincsKeypair,
  WasmShrincsAccount,
} from "./nodejs/hashsigs_rs.js";

// ── compile-time conformance (zero emit, zero runtime) ─────────────────────
import type {
  StatefulSignResult as _StatefulSignResult,
  WasmShrincsKeypair as _WasmShrincsKeypair,
} from "./nodejs/hashsigs_rs.js";

// type _Expect<T extends true> = T;
// type _Equal<A, B> =
//   (<T>() => T extends A ? 1 : 2) extends (<T>() => T extends B ? 1 : 2)
//     ? true
//     : false;

// type _KeygenMintsExportedKeypair = _Expect<
//   _Equal<ReturnType<ShrincsWasmModule["shrincsKeygen"]>, _WasmShrincsKeypair>
// >;
// type _SignStatefulRawReturnsSignResult = _Expect<
//   _Equal<ReturnType<_WasmShrincsKeypair["signStatefulRaw"]>, _StatefulSignResult>
// >;
