// Browser loader.
//
// The browser build is wasm-bindgen's `web` target: an ES module whose default
// export instantiates the wasm from bytes. We inline the wasm as base64
// (generated by scripts/gen-wasm-inline.mjs) and instantiate from those bytes so
// there is no separate `.wasm` asset to resolve — this works in any bundler with
// zero configuration, at the cost of a ~33% larger payload.
import init, * as wasm from "./web/hashsigs_rs.js";
import { wasmBase64 } from "./web/inline.js";

type ShrincsWasmModule = typeof wasm;

let cached: Promise<ShrincsWasmModule> | undefined;

export async function loadShrincsWasm(): Promise<ShrincsWasmModule> {
  if (cached) return cached;
  cached = (async () => {
    const bytes = Uint8Array.from(atob(wasmBase64), (c) => c.charCodeAt(0));
    await init({ module_or_path: bytes });
    return wasm;
  })().catch((err) => {
    cached = undefined;
    throw err;
  });
  return cached;
}
